In [2]:
import pandas as pd
import re

# 数据集的导入和基本信息的查询

In [3]:
# line.decode("utf-8","ignore")
# 读取数据
dataPath = './data/BA_AirlineReviews.csv'
data = pd.read_csv(dataPath, encoding='latin-1')

data.head(5)

,Unnamed: 0,OverallRating,ReviewHeader,Name,Datetime,VerifiedReview,ReviewBody,TypeOfTraveller,SeatType,Route,DateFlown,SeatComfort,CabinStaffService,GroundService,ValueForMoney,Recommended,Aircraft,Food&Beverages,InflightEntertainment,Wifi&Connectivity
0,0,1.8,"""Service level far worse then Ryanair""",L Keele,19th November 2023,True,4 Hours before takeoff we received a Mail stat...,Couple Leisure,Economy Class,London to Stuttgart,23-Nov,1.0,1.0,1.0,1.0,no,NaN,NaN,NaN,NaN
1,1,2.4,"""do not upgrade members based on status""",Austin Jones,19th November 2023,True,I recently had a delay on British Airways from...,Business,Economy Class,Brussels to London,23-Nov,2.0,3.0,1.0,2.0,no,A320,1.0,2.0,2.0
2,2,7.1,"""Flight was smooth and quick""",M A Collie,16th November 2023,False,"Boarded on time, but it took ages to get to th...",Couple Leisure,Business Class,London Heathrow to Dublin,23-Nov,3.0,3.0,4.0,3.0,yes,A320,4.0,NaN,NaN
3,3,1.3,"""Absolutely hopeless airline""",Nigel Dean,16th November 2023,True,"5 days before the flight, we were advised by B...",Couple Leisure,Economy Class,London to Dublin,22-Dec,3.0,3.0,1.0,1.0,no,NaN,NaN,NaN,NaN
4,4,0.6,"""Customer Service is non existent""",Gaylynne Simpson,14th November 2023,False,"We traveled to Lisbon for our dream vacation, ...",Couple Leisure,Economy Class,London to Lisbon,23-Nov,1.0,1.0,1.0,1.0,no,Boeing 747,1.0,1.0,1.0

In [4]:
# 查看数据集大小
data.shape

(3701, 20)

# 数据清洗

## 删除无关特征

In [5]:
# 查看数据的列名
columns = data.columns.tolist()
print(columns)

['Unnamed: 0', 'OverallRating', 'ReviewHeader', 'Name', 'Datetime', 'VerifiedReview', 'ReviewBody', 'TypeOfTraveller', 'SeatType', 'Route', 'DateFlown', 'SeatComfort', 'CabinStaffService', 'GroundService', 'ValueForMoney', 'Recommended', 'Aircraft', 'Food&Beverages', 'InflightEntertainment', 'Wifi&Connectivity']

In [6]:
# 删除一些本次作业用不上的列
columns_to_drop = ['Unnamed: 0', 'ReviewBody', 'Name', 'Datetime', 'VerifiedReview', 'ValueForMoney', 'Recommended']
data = data.drop(columns=columns_to_drop)
data.head()

,OverallRating,ReviewHeader,TypeOfTraveller,SeatType,Route,DateFlown,SeatComfort,CabinStaffService,GroundService,Aircraft,Food&Beverages,InflightEntertainment,Wifi&Connectivity
0,1.8,"""Service level far worse then Ryanair""",Couple Leisure,Economy Class,London to Stuttgart,23-Nov,1.0,1.0,1.0,NaN,NaN,NaN,NaN
1,2.4,"""do not upgrade members based on status""",Business,Economy Class,Brussels to London,23-Nov,2.0,3.0,1.0,A320,1.0,2.0,2.0
2,7.1,"""Flight was smooth and quick""",Couple Leisure,Business Class,London Heathrow to Dublin,23-Nov,3.0,3.0,4.0,A320,4.0,NaN,NaN
3,1.3,"""Absolutely hopeless airline""",Couple Leisure,Economy Class,London to Dublin,22-Dec,3.0,3.0,1.0,NaN,NaN,NaN,NaN
4,0.6,"""Customer Service is non existent""",Couple Leisure,Economy Class,London to Lisbon,23-Nov,1.0,1.0,1.0,Boeing 747,1.0,1.0,1.0

In [7]:
# 查看数据集大小
data.shape

(3701, 13)

## 处理空缺值

In [8]:
# 计算数据每列的空缺率
missing_values = data.isna().sum() / len(data)
print(missing_values)

OverallRating            0.001351
ReviewHeader             0.000000
TypeOfTraveller          0.208322
SeatType                 0.000540
Route                    0.209403
DateFlown                0.210213
SeatComfort              0.031343
CabinStaffService        0.034315
GroundService            0.228587
Aircraft                 0.073764
Food&Beverages           0.104296
InflightEntertainment    0.310727
Wifi&Connectivity        0.835450
dtype: float64

In [9]:
# 再删除一些空缺率高的列
columns_to_drop = ['InflightEntertainment', 'Wifi&Connectivity']
data = data.drop(columns=columns_to_drop)
data.head()

,OverallRating,ReviewHeader,TypeOfTraveller,SeatType,Route,DateFlown,SeatComfort,CabinStaffService,GroundService,Aircraft,Food&Beverages
0,1.8,"""Service level far worse then Ryanair""",Couple Leisure,Economy Class,London to Stuttgart,23-Nov,1.0,1.0,1.0,NaN,NaN
1,2.4,"""do not upgrade members based on status""",Business,Economy Class,Brussels to London,23-Nov,2.0,3.0,1.0,A320,1.0
2,7.1,"""Flight was smooth and quick""",Couple Leisure,Business Class,London Heathrow to Dublin,23-Nov,3.0,3.0,4.0,A320,4.0
3,1.3,"""Absolutely hopeless airline""",Couple Leisure,Economy Class,London to Dublin,22-Dec,3.0,3.0,1.0,NaN,NaN
4,0.6,"""Customer Service is non existent""",Couple Leisure,Economy Class,London to Lisbon,23-Nov,1.0,1.0,1.0,Boeing 747,1.0

In [10]:
# 删除含有空缺值的数据
data.dropna(inplace=True)

In [11]:
# 检查每列的空缺率
missing_values = data.isna().sum() / len(data)
print(missing_values)

OverallRating        0.0
ReviewHeader         0.0
TypeOfTraveller      0.0
SeatType             0.0
Route                0.0
DateFlown            0.0
SeatComfort          0.0
CabinStaffService    0.0
GroundService        0.0
Aircraft             0.0
Food&Beverages       0.0
dtype: float64

In [12]:
data.shape

(2528, 11)

## 文本规范化

In [13]:
# 纠正一些机型中存在错误
data['Aircraft'] = data['Aircraft'].replace('Boeing 747- 400', 'Boeing 747-400')
data['Aircraft'] = data['Aircraft'].replace('Boeing 747 400', 'Boeing 747-400')
data['Aircraft'] = data['Aircraft'].replace('E-170', 'E170')
data['Aircraft'] = data['Aircraft'].replace('E-190', 'E190')
data['Aircraft'] = data['Aircraft'].replace('Embraer170', 'Embraer 170')
data['Aircraft'] = data['Aircraft'].replace('Embraer-190', 'Embraer 190')

## 增加新字段

In [14]:
# 提取文本中的月份
data['DateFlown'] = data['DateFlown'].str.split('-').str[1]
data['DateFlown']

1       Nov
2       Nov
4       Nov
5       Sep
6       Nov
       ...
2915    Jun
2916    Jun
2917    May
2918    Jun
2919    May
Name: DateFlown, Length: 2528, dtype: object

In [15]:
# 定义一个函数来提取城市名称并拆分成两部分
def split_route(route):
    match = re.match(r'(.+) to (.+)', route)
    if match:
        return match.group(1), match.group(2)
    else:
        return None, None

# 创建两个新列
data['Departure'], data['Destination'] = zip(*data['Route'].apply(split_route))

# 删除原始的 Route 列
data.drop(columns=['Route'], inplace=True)

In [16]:
# 定义要替换的字典，键是要被替换的值，值是替换后的新值
replace_dict = {"LHR": "Heathrow", "London Heathrow": "Heathrow", "LGW": "Gatwick", "London Gatwick": "Gatwick", 
                "BKK": "Suvarnabhumi", "MAN": "Manchester", "JFK": "John F. Kennedy", "GLA": "Glasgow", 
                "LCY": "London", "SIN": "Singapore", "YYZ": "Toronto", "ATH": "Athens", "MIA": "Miami", 
                "JNB": "O.R. Tambo", "SFO": "San Francisco", "AMS": "Amsterdam", "YVR": "Vancouver", "HKG": "Hong Kong", 
                "London ": "London", "CPT": "Cape Town", "KUL": "Kuala Lumpur", "GVA": "Geneva", "DXB": "Dubai" , 
                "BOS": "Boston", "EDI": "Edinburgh", "BGI": "Grantley Adams"}
# 使用循环遍历字典中的每一对键值对，使用when函数进行条件判断，并使用withColumn方法进行替换
for old_value, new_value in replace_dict.items():
    data['Departure'] = data['Departure'].replace(old_value, new_value)
    data['Destination'] = data['Destination'].replace(old_value, new_value)

In [17]:
data.shape

(2528, 12)

In [19]:
data.to_csv('./data/processedData.csv', index = False)